### ISSUE TITLE
Database gateway needs refactoring

### ISSUE THREAD

**Issue by SirRAL** [CSC207-UofT/course-project-024#29]
The gateway interface is fully implemented as a MySQL-linked class-like. It needs to be separated out as a database-agnostic boundary that 1) doesn't implement any database specific syntax, that should be done by an implementer 2) doesn't reference any Entities in order to respect Clean Architecture.

**Comment by AbdusShaikh** [comment]
Database gateway now implements the separate interface "DataBaseTools".
This change means a new gateway can be built off of DataBaseTools, and so coupling between the database and program is reduced
